import com.android.build.api.variant.DeviceTestBuilder
import com.android.build.api.variant.HostTestBuilder

plugins {
    id("com.android.library")
}

android {
    namespace = "com.mqvpn.sdk.native_"
    compileSdk = 37
    // Pin the NDK used for the JNI wrapper build. Without this, AGP falls
    // back to its bundled default, which breaks environments that provision
    // a specific NDK via ndk.dir (e.g. the F-Droid buildserver). Keep in
    // sync with `ndk:` in fdroiddata's metadata/com.mqvpn.app.yml.
    ndkVersion = "28.2.13676358"

    defaultConfig {
        minSdk = 26
        consumerProguardFiles("consumer-rules.pro")
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"

        externalNativeBuild {
            cmake {
                // Reproducible-build hygiene for the JNI wrapper: strip the
                // checkout path from __FILE__/debug info, and drop the linker
                // build-id (it hashes pre-strip debug info, which embeds
                // paths). Together with the -ffile-prefix-map flags in
                // scripts/build_android.sh this makes the APK byte-identical
                // across build directories.
                cFlags("-ffile-prefix-map=${rootProject.projectDir.parentFile}=/mqvpn")
                arguments("-DCMAKE_SHARED_LINKER_FLAGS=-Wl,--build-id=none")
            }
        }

        ndk {
            // Only ABIs with prebuilt .a files (build_android.sh output).
            // Default stays arm64-v8a (release output unchanged). The
            // emulator CI job overrides with -PmqvpnAbiFilters=x86_64 after
            // building x86_64 prebuilts, so connectedAndroidTest can run on
            // a GitHub-hosted x86_64 emulator.
            val abis = (project.findProperty("mqvpnAbiFilters") as String?)
                ?.split(',')?.map { it.trim() } ?: listOf("arm64-v8a")
            abiFilters += abis
        }
    }

    buildTypes {
        getByName("debug") {
            // Test-only JNI entry points (NativeBridgeTestSeams) are compiled
            // only into the debug .so; release exports none of them.
            externalNativeBuild {
                cmake {
                    arguments("-DMQVPN_JNI_TEST_SEAMS=ON")
                }
            }
        }
    }

    externalNativeBuild {
        cmake {
            path = file("src/main/jni/CMakeLists.txt")
            version = "3.22.1"
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }

    testOptions {
        unitTests {
            // android.* stubs return defaults instead of throwing; the pure
            // Kotlin units under test never call them.
            isReturnDefaultValues = true
        }
    }
}

// Certificate fixtures come from the repo's tests/certs (single source of
// truth, regenerated by gen_chain.sh). They are copied into distinct
// generated directories per source set: AGP does not allow one directory to
// be shared by two source sets, and nothing is committed twice.
val certFixturesDir = rootProject.file("../tests/certs")
val certFixturesForUnitTest = layout.buildDirectory.dir("generated/certFixtures/test")
val certFixturesForAndroidTest = layout.buildDirectory.dir("generated/certFixtures/androidTest")
val certRootResForAndroidTest = layout.buildDirectory.dir("generated/certFixtures/androidTestRes")

// AGP 9's source-set decorator (DefaultAndroidLibrarySourceSet_Decorated)
// cannot be cast back to AndroidLibrarySourceSet when a generated directory
// is attached via `android.sourceSets…srcDir(...)` — that form throws a
// ClassCastException at configuration time. Use the variant API instead: a
// task with a DirectoryProperty output, wired via addGeneratedSourceDirectory.
abstract class CopyCertFixtures @javax.inject.Inject constructor(private val fs: FileSystemOperations) : DefaultTask() {
    @get:InputFiles abstract val sources: ConfigurableFileCollection
    /** Single-file sources only: rename applies to every copied file. */
    @get:Input @get:Optional abstract val renameTo: Property<String>
    /** Subdirectory below outputDir (e.g. "raw" for an Android res root). */
    @get:Input @get:Optional abstract val intoSubdir: Property<String>
    @get:OutputDirectory abstract val outputDir: DirectoryProperty
    @TaskAction fun run() {
        renameTo.orNull?.let { require(sources.files.size == 1) { "renameTo needs exactly one source file" } }
        // sync, not copy: the output directory is task-owned, so a fixture removed
        // or renamed in tests/certs must disappear here too (no stale copies)
        fs.sync {
            from(sources)
            into(intoSubdir.orNull?.let { outputDir.dir(it) } ?: outputDir)
            renameTo.orNull?.let { n -> rename { n } }
        }
    }
}
val copyCertFixturesForUnitTest = tasks.register<CopyCertFixtures>("copyCertFixturesForUnitTest") {
    sources.from(fileTree(certFixturesDir) { include("*.der") })
    outputDir.set(certFixturesForUnitTest)
}
val copyCertFixturesForAndroidTest = tasks.register<CopyCertFixtures>("copyCertFixturesForAndroidTest") {
    sources.from(fileTree(certFixturesDir) { include("*.der") })
    outputDir.set(certFixturesForAndroidTest)
}
// @raw/chain_root for the androidTest network security config: an Android
// res root needs a <type>/ subdirectory, so the file lands in raw/ below the
// registered directory (the resource name derives from the file name).
val copyCertRootResForAndroidTest = tasks.register<CopyCertFixtures>("copyCertRootResForAndroidTest") {
    sources.from(certFixturesDir.resolve("chain-root.der"))
    renameTo.set("chain_root.der")
    intoSubdir.set("raw")
    outputDir.set(certRootResForAndroidTest)
}
// AGP 9.4 hides LibraryVariant.unitTest/androidTest (superseded by the
// multi-test-suite hostTests/deviceTests maps); look the components up by
// their well-known keys.
androidComponents.onVariants { v ->
    val unitTest = v.hostTests[HostTestBuilder.UNIT_TEST_TYPE]
    val androidTest = v.deviceTests[DeviceTestBuilder.ANDROID_TEST_TYPE]
    unitTest?.sources?.resources?.addGeneratedSourceDirectory(copyCertFixturesForUnitTest) { it.outputDir }
    androidTest?.sources?.resources?.addGeneratedSourceDirectory(copyCertFixturesForAndroidTest) { it.outputDir }
    androidTest?.sources?.res?.addGeneratedSourceDirectory(copyCertRootResForAndroidTest) { it.outputDir }
}

dependencies {
    implementation("androidx.annotation:annotation:1.9.1")
    testImplementation("junit:junit:4.13.2")
    androidTestImplementation("androidx.test.ext:junit:1.3.0")
    androidTestImplementation("androidx.test:runner:1.7.0")
}
